#!/bin/bash
# Kubeadm join script for worker nodes
# Generated by Terraform

# This script is meant to be run on worker nodes to join the Kubernetes cluster
# Execute this after obtaining the join command from the control plane:
#
# On control plane node:
# sudo kubeadm token create --print-join-command
#
# Then run the output command on worker nodes

# Example join command (requires values from control plane):
# sudo kubeadm join ${control_plane_ip}:6443 --token <token> \
#   --discovery-token-ca-cert-hash sha256:<hash>

# For production, obtain the actual token and hash from the control plane
